### ISSUE TITLE
Class "MFMessageComposeViewController" referenced by type encoding not found at runtime.

### ISSUE THREAD

**Issue by fpaaske** [msywensky/nativescript-phone#51]
Hi, 

I get this error after updating my test phone to iOS 14.5 Beta, and it happens when we use sms() somewhere in the code.
Could you help with fixing this?

```
  "dependencies": {
    "@nativescript/core": "~6.5.20",
    "nativescript-phone": "^2.0.0",
```

```
import * as Phone from "nativescript-phone";
Phone.sms(['99999999'], 'Hello').then(r => console.log('sms')); // removing this line resolves the issue
```

You don't even have to actually call the method, it's enough to just have it in the code. The app will crash during startup.
This is the error I get:

```
default	13:43:21.395615+0100	demo	*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Class "MFMessageComposeViewController" referenced by type encoding not found at runtime.'
*** First throw call stack:
(0x19fbd7060 0x1b3e69460 0x1013e0934 0x1013e1090 0x1013c8498 0x1013b3e50 0x1013ca2d8 0x1013b942c 0x1013be83c 0x1013c1628 0x101f037cc 0x101f00f28 0x101f00f28 0x101f00e80 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00e80 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00e80 0x101f00e80 0x101f00e80 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101ee25e8 0x101490e48 0x101b915f4 0x101c1273c 0x101c02ee4 0x1017a64d4 0x101ef0080 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101f00f28 0x101ee25e8 0x101490e48 0x101ba7e20 0x101f037cc 0x101f00f28 0x101ee25e8 0x101490e48 0x1013cb8e8 0x1013cb2f4 0x1013cc428 0x101f37388 0x101f381b4 0x1<…>
default	13:43:21.395834+0100	demo	NativeScript caught signal 6.
default	13:43:21.395931+0100	demo	Native Stack:
default	13:43:21.396105+0100	demo	1   0x1013db018 sig_handler(int)
default	13:43:21.396192+0100	demo	2   0x1e8117d9c <redacted>
default	13:43:21.396280+0100	demo	3   0x1e81279c4 pthread_kill
default	13:43:21.396399+0100	demo	4   0x1a8d40a44 abort
default	13:43:21.396591+0100	demo	5   0x1b3f43be8 <redacted>
default	13:43:21.396744+0100	demo	6   0x1b3f35d14 <redacted>
default	13:43:21.396830+0100	demo	7   0x1b3e49960 <redacted>
default	13:43:21.397017+0100	demo	8   0x1b3f43074 <redacted>
default	13:43:21.397106+0100	demo	9   0x1b3f4599c __cxa_get_exception_ptr
default	13:43:21.397316+0100	demo	10  0x1b3f4595c <redacted>
default	13:43:21.397464+0100	demo	11  0x1b3e69588 objc_exception_rethrow
default	13:43:21.397696+0100	demo	12  0x1013e0934 NativeScript::TypeFactory::parseType(NativeScript::GlobalObject*, Metadata::TypeEncoding const*&, bool)
default	13:43:21.397835+0100	demo	13  0x1013e1090 NativeScript::TypeFactory::parseTypes(NativeScript::GlobalObject*, Metadata::TypeEncoding const*&, int, bool)
default	13:43:21.397896+0100	demo	14  0x1013c8498 NativeScript::ObjCMethodWrapper::finishCreation(JSC::VM&, NativeScript::GlobalObject*, WTF::HashSet<Metadata::MemberMeta const*, WTF::PtrHash<Metadata::MemberMeta const*>, WTF::HashTraits<Metadata::MemberMeta const*> >)
default	13:43:21.397950+0100	demo	15  0x1013b3e50 NativeScript::ObjCMethodWrapper::create(JSC::VM&, NativeScript::GlobalObject*, JSC::Structure*, WTF::HashSet<Metadata::MemberMeta const*, WTF::PtrHash<Metadata::MemberMeta const*>, WTF::HashTraits<Metadata::MemberMeta const*> >)
default	13:43:21.398036+0100	demo	16  0x1013ca2d8 NativeScript::overrideObjcMethodCalls(JSC::ExecState*, JSC::JSObject*, JSC::PropertyName, JSC::JSCell*, Metadata::BaseClassMeta const*, Metadata::MemberType, objc_class*, WTF::Vector<Metadata::ProtocolMeta const*, 0ul, WTF::CrashOnOverflow, 16ul> const&)
default	13:43:21.398161+0100	demo	17  0x1013b942c NativeScript::ObjCClassBuilder::addInstanceMethod(JSC::ExecState*, JSC::Identifier const&, JSC::JSCell*)
default	13:43:21.398217+0100	demo	18  0x1013be83c NativeScript::ObjCClassBuilder::addInstanceMembers(JSC::ExecState*, JSC::JSObject*, JSC::JSValue)
default	13:43:21.398272+0100	demo	19  0x1013c1628 NativeScript::ObjCExtendFunction(JSC::ExecState*)
default	13:43:21.398425+0100	demo	20  0x101f037cc llint_entry
default	13:43:21.398544+0100	demo	21  0x101f00f28 llint_entry
default	13:43:21.398605+0100	demo	22  0x101f00f28 llint_entry
default	13:43:21.398655+0100	demo	23  0x101f00e80 llint_entry
default	13:43:21.398708+0100	demo	24  0x101f00f28 llint_entry
default	13:43:21.398758+0100	demo	25  0x101f00f28 llint_entry
default	13:43:21.398799+0100	demo	26  0x101f00f28 llint_entry
default	13:43:21.398843+0100	demo	27  0x101f00e80 llint_entry
default	13:43:21.398920+0100	demo	28  0x101f00f28 llint_entry
default	13:43:21.399158+0100	demo	29  0x101f00f28 llint_entry
default	13:43:21.399219+0100	demo	30  0x101f00f28 llint_entry
default	13:43:21.399281+0100	demo	31  0x101f00e80 llint_entry
default	13:43:21.399343+0100	demo	JS Stack:
default	13:43:21.399451+0100	demo	extend([native code])
at ../node_modules/nativescript-phone/index.js(file:///app/vendor.js:54103:67)
at __webpack_require__(file:///app/runtime.js:751:34)
at fn(file:///app/runtime.js:121:39)
at file:///app/bundle.js:394:95
at ./main-view-model.ts(file:///app/bundle.js:536:34)
at __webpack_require__(file:///app/runtime.js:751:34)
at fn(file:///app/runtime.js:121:39)
at file:///app/bundle.js:327:93
at ./main-page.ts(file:///app/bundle.js:362:34)
at __webpack_require__(file:///app/runtime.js:751:34)
at fn(file:///app/runtime.js:121:39)
at webpackContext(file:///app/bundle.js:166:28)
at loader(file:///app/vendor.js:7089:35)
at loadModule(file:///app/vendor.js:7130:39)
at file:///app/vendor.js:15179:75
at file:///app/vendor.js:22594:57
at valueChanged(file:///app/vendor.js:23026:23)
at file:///app/vendor.js:17062:37
at setPropertyValue(file:///app/vendor.js:15869:17)
at file:///app/vendor.js:15829:33
at getComponentModule(file:///app/vendor.js:15841:29)
at file:///app/vendor.js:15587:62
at file:///app/ve<…>
```

**Comment by JCpoz123** [comment]
Same issue, app crashes at startup after 14.5 update.  We don't even use the SMS method, only the "dial" method,

**Comment by pbelko** [comment]
also only use the 'dial' method and its crashing at startup for us

**Comment by Sarfaraaz** [comment]
I have yet to confirm this on a real device, but I managed to get past the crashing by linking the `Messages` framework to the project.

Add this to build.xcconfig (or simply link the framework in xcode if you use that).
```
OTHER_LDFLAGS = $(inherited) -framework Messages
```

**Comment by bradmartin** [comment]
I poked around at updating this yesterday. However, it would be a breaking change moving away from the promise based approach and using the event system with NS `Observable` to handle success/fail/cancel of SMS.

During the testing on an actual iPhone, it works well and I have not been able to reproduce a crash.

If anyone is interested in a refactor of this to update it, you can thumbs up this and I'll double check if I have permissions to the npm package, if not I can drop a tgz here push to a branch here for the meantime.

**Comment by bradmartin** [comment]
[nativescript-phone-3.0.0.tgz.zip](https://github.com/msywensky/nativescript-phone/files/6406001/nativescript-phone-3.0.0.tgz.zip)

**Comment by bradmartin** [comment]
This is what the approach would be with the new event system approach:

```ts
import {
  NSPhoneEventEmitter,
  sms,
  dial,
  requestCallPermission,
  SMSEvents,
  DialEvents
} from 'nativescript-phone';

NSPhoneEventEmitter.on(SMSEvents.FAILED, args => {
  console.log('FAILED', args.data);
});

NSPhoneEventEmitter.on(SMSEvents.SUCCESS, args => {
  console.log('SMS Successful');
});

phone.NSPhoneEventEmitter.on(SMSEvents.CANCELLED, args => {
  console.log('SMS Cancelled');
});

NSPhoneEventEmitter.on(SMSEvents.ERROR, args => {
  console.log('SMS ERROR', args.data);
});

NSPhoneEventEmitter.on(SMSEvents.UNKNOWN, args => {
  console.log('SMS UNKNOWN', args.data);
});

sms(['212-555-1234'], 'testing');
```

Of course, you don't have to listen for any of the events if you don't need to respond to them.

**Comment by jaseowens** [comment]
Proposed changes are working for my project. Though is worth noting we do not make use of the sms functionality, only dial, but with the changes my project is no longer crashing on 14.5.

**Comment by octo888** [comment]
Any updates?

**Comment by bradmartin** [comment]
I believe the tgz I posted you can use fine for now in your project (just download and point your dep to the local file path of the tgz, npm handles the rest), officially I don't think I have npm publish rights for this. So if @msywensky is around and could merge a PR and publish we'd be good to update it with the breaking changes.

**Comment by Sarfaraaz** [comment]
For what it's worth, the comment I've left above https://github.com/msywensky/nativescript-phone/issues/51#issuecomment-829569926 solves the crashing without the need for any change to your codebase. We've been stable since that fix in prod. I do have to emphasize that we do not use the sms fuctionality, so you'll have to check and verify if it works.

I look forward to seeing the changes @bradmartin made published, as it's a much nicer implementation. I do feel like the breaking change note should be emphasized more in the readme under some form of changelog.

**Comment by bradmartin** [comment]
I went ahead and published 3.0.1 (minor fix on the bug version) to npm with the new approach which fixes this issue (without using the flag @Sarfaraaz mentioned). I don't have time to make a proper changelog right now, but I did add a note to the README about the 3.x.x breaking change event system approach.

**Comment by sqa-vitalii** [comment]
bradmartin
Thank you for your help! 
Actually I took your changes for dial and sms methods, and changed sources locally (because I have NS 6 in my project)

Sarfaraaz 
Thank you too, but your solution solves crashes issue, but sms and dial methods didn't work for me with it

**Comment by octo888** [comment]
bradmartin
Thank you for your help!
Actually I took your changes for dial and sms methods, and changed sources locally (because I have NS 6 in my project)

Sarfaraaz
Thank you too, but your solution solves crashes issue, but sms and dial methods didn't work for me with it
